### ISSUE TITLE
reduce number of workers in external-provisioner

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#861]
The default is to start hundreds of worker goroutines. With distributed provisioning, each node is very unlikely to create that many volumes in parallel. We can safe some resources and (perhaps more importantly) make panic dumps much shorter when we spawn less goroutines.

See https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pmem-csi/branches/devel/runs/303/nodes/88/steps/151/log/?start=0:
```
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: goroutine 31 [running]:
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: k8s.io/klog/v2.stacks(0xc0000ae001, 0xc00069c000, 0x57, 0x1dd)
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: k8s.io/klog/v2.(*loggingT).output(0x2604640, 0xc000000003, 0x0, 0x0, 0xc0001ecd20, 0x2553078, 0xd, 0x57, 0x0)
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: k8s.io/klog/v2.(*loggingT).printf(0x2604640, 0x3, 0x0, 0x0, 0x0, 0x0, 0x19a584d, 0x26, 0x0, 0x0, ...)
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/k8s.io/klog/v2/klog.go:750 +0x191
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: k8s.io/klog/v2.Fatalf(...)
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/k8s.io/klog/v2/klog.go:1502
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: github.com/kubernetes-csi/csi-lib-utils/connection.ExitOnConnectionLoss.func1(0x2604640)
[2021-01-21T18:14:34.385Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go:87 +0x1d4
...
2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: goroutine 299 [sync.Cond.Wait]:
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: runtime.goparkunlock(...)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/go/pkg/csiprow.XXXXnhlINB/go-1.15/src/runtime/proc.go:312
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: sync.runtime_notifyListWait(0xc000528490, 0x27)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/go/pkg/csiprow.XXXXnhlINB/go-1.15/src/runtime/sema.go:513 +0xf8
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: sync.(*Cond).Wait(0xc000528480)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/go/pkg/csiprow.XXXXnhlINB/go-1.15/src/sync/cond.go:56 +0x9d
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: k8s.io/client-go/util/workqueue.(*Type).Get(0xc0002fef00, 0x0, 0x0, 0x0)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/k8s.io/client-go/util/workqueue/queue.go:145 +0x89
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextVolumeWorkItem(0xc000423b80, 0x1ba49c0, 0xc00009c008, 0x0)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:993 +0x3e
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).runVolumeWorker(0xc000423b80, 0x1ba49c0, 0xc00009c008)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:932 +0x3f
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1.3()
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:884 +0x3c
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006af880)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006af880, 0x1b66080, 0xc000629680, 0x1, 0x0)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006af880, 0x3b9aca00, 0x0, 0x1, 0x0)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: k8s.io/apimachinery/pkg/util/wait.Until(0xc0006af880, 0x3b9aca00, 0x0)
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
[2021-01-21T18:14:34.862Z] pmem-csi-intel-com-node-86n58/external-provisioner@pmem..ker1: 	/workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:884 +0x3d6
```

**Comment by pohly** [comment]
Resolved by PR #890
