### ISSUE TITLE
test flake: assignment to nil map in operator deployment

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#864]
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-860/6/pipeline

```
[2021-01-23T02:00:22.076Z] Jan 23 02:00:21.862: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
[2021-01-23T02:00:22.076Z] panic: assignment to entry in nil map
[2021-01-23T02:00:22.076Z] 
[2021-01-23T02:00:22.076Z] goroutine 1756272 [running]:
[2021-01-23T02:00:22.076Z] github.com/intel/pmem-csi/test/e2e/operator.glob..func2.1.1(0xc0007cc080, 0xc0000b90f8)
[2021-01-23T02:00:22.076Z] 	/mnt/workspace/pmem-csi_PR-860/test/e2e/operator/deployment_api.go:106 +0x20b
[2021-01-23T02:00:22.076Z] created by github.com/intel/pmem-csi/test/e2e/operator.glob..func2.1
[2021-01-23T02:00:22.076Z] 	/mnt/workspace/pmem-csi_PR-860/test/e2e/operator/deployment_api.go:99 +0x873
[2021-01-23T02:00:22.076Z] FAIL	github.com/intel/pmem-csi/test/e2e	14455.988s
```

I suspect that this is a race between

https://github.com/intel/pmem-csi/blob/e521220167b19164fea60d1f9f4b10dbe2ce599f/test/e2e/operator/deployment_api.go#L106

and

https://github.com/intel/pmem-csi/blob/e521220167b19164fea60d1f9f4b10dbe2ce599f/test/e2e/operator/deployment_api.go#L120

**Comment by pohly** [comment]
The right solution is to wait for the goroutine to stop while cleaning up.
