### ISSUE TITLE
data race: json encoding/decoding

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#871]

**Comment by pohly** [comment]
From https://github.com/intel/pmem-csi/pull/866#issuecomment-770333363:
```
[2021-01-30T10:30:44.797Z] ?   	github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller	[no test files]
[2021-01-30T10:31:19.390Z] fatal error: concurrent map read and map write
[2021-01-30T10:31:19.390Z] 
[2021-01-30T10:31:19.390Z] goroutine 840 [running]:
[2021-01-30T10:31:19.390Z] runtime.throw(0x17ba129, 0x21)
[2021-01-30T10:31:19.390Z] 	/go/src/runtime/panic.go:1116 +0x72 fp=0xc000c5a5f8 sp=0xc000c5a5c8 pc=0x439552
[2021-01-30T10:31:19.390Z] runtime.mapaccess2(0x15fe060, 0xc0001bcbd0, 0xc00057f5a0, 0xc00057f5a0, 0xc001068a02)
[2021-01-30T10:31:19.390Z] 	/go/src/runtime/map.go:469 +0x25b fp=0xc000c5a638 sp=0xc000c5a5f8 pc=0x41147b
[2021-01-30T10:31:19.390Z] reflect.mapaccess(0x15fe060, 0xc0001bcbd0, 0xc00057f5a0, 0x17adb9e)
[2021-01-30T10:31:19.390Z] 	/go/src/runtime/map.go:1309 +0x3f fp=0xc000c5a670 sp=0xc000c5a638 pc=0x46ab3f
[2021-01-30T10:31:19.390Z] reflect.Value.MapIndex(0x15fe060, 0xc00043cf08, 0x195, 0x15896a0, 0xc00057f5a0, 0x98, 0x4ebd05, 0xc0006a7970, 0x179d096)
[2021-01-30T10:31:19.390Z] 	/go/src/reflect/value.go:1188 +0x16e fp=0xc000c5a6e8 sp=0xc000c5a670 pc=0x4d634e
[2021-01-30T10:31:19.390Z] encoding/json.mapEncoder.encode(0x1846648, 0xc000be9a80, 0x15fe060, 0xc00043cf08, 0x195, 0x15d0100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:801 +0x30d fp=0xc000c5a860 sp=0xc000c5a6e8 pc=0x57fecd
[2021-01-30T10:31:19.390Z] encoding/json.mapEncoder.encode-fm(0xc000be9a80, 0x15fe060, 0xc00043cf08, 0x195, 0xc000430100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:777 +0x65 fp=0xc000c5a8a0 sp=0xc000c5a860 pc=0x58c2c5
[2021-01-30T10:31:19.390Z] encoding/json.ptrEncoder.encode(0xc000424790, 0xc000be9a80, 0x160ff00, 0xc00043cf08, 0x16, 0x1600100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:915 +0x125 fp=0xc000c5a960 sp=0xc000c5a8a0 pc=0x580ee5
[2021-01-30T10:31:19.390Z] encoding/json.ptrEncoder.encode-fm(0xc000be9a80, 0x160ff00, 0xc00043cf08, 0x16, 0x2310100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:900 +0x65 fp=0xc000c5a9a0 sp=0xc000c5a960 pc=0x58c445
[2021-01-30T10:31:19.390Z] encoding/json.(*encodeState).reflectValue(0xc000be9a80, 0x160ff00, 0xc00043cf08, 0x16, 0xc000c50100)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:358 +0x82 fp=0xc000c5a9d8 sp=0xc000c5a9a0 pc=0x57d062
[2021-01-30T10:31:19.390Z] encoding/json.(*encodeState).marshal(0xc000be9a80, 0x160ff00, 0xc00043cf08, 0xc000060100, 0x0, 0x0)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/encode.go:330 +0xf4 fp=0xc000c5aa38 sp=0xc000c5a9d8 pc=0x57cc54
[2021-01-30T10:31:19.390Z] encoding/json.(*Encoder).Encode(0xc000c5aaf8, 0x160ff00, 0xc00043cf08, 0xc000068800, 0x7fb2fc0407d0)
[2021-01-30T10:31:19.390Z] 	/go/src/encoding/json/stream.go:206 +0x8b fp=0xc000c5aac8 sp=0xc000c5aa38 pc=0x589dab
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/types.(*NodeSelector).String(0xc00043cf08, 0xc00043cf08, 0xb0)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/types/types.go:37 +0xb0 fp=0xc000c5ab58 sp=0xc000c5aac8 pc=0xc12390
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/deployments.LoadAndCustomizeObjects.func1(0xc000721d00)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/deployments/load.go:84 +0xd65 fp=0xc000c5afe0 sp=0xc000c5ab58 pc=0x13ff2a5
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/deployments.loadYAML(0xc0000419e0, 0x28, 0xc000c5b228, 0xc000c5b218, 0xc000c5b208, 0xc0000419e0, 0x28, 0x179cfee, 0x4, 0x179eb01)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/deployments/load.go:328 +0x60b fp=0xc000c5b160 sp=0xc000c5afe0 pc=0x13fe50b
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/deployments.LoadAndCustomizeObjects(0x1, 0x14, 0x179cbc2, 0x3, 0x17a4e67, 0xe, 0xc0009db820, 0x11, 0xc0009db840, 0x1a, ...)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/deployments/load.go:160 +0x1d8 fp=0xc000c5b278 sp=0xc000c5b160 pc=0x13fc418
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/test/e2e/operator/validate.DriverDeployment(0x1999e40, 0xc000cf1600, 0x1, 0x14, 0x17a4e67, 0xe, 0xc0009db820, 0x11, 0xc0009db840, 0x1a, ...)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/test/e2e/operator/validate/validate.go:125 +0x205 fp=0xc000c5b950 sp=0xc000c5b278 pc=0x1400ec5
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.5(0xc000753e60, 0xc000f24000, 0xc000310c60, 0x2, 0x2, 0x1)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:359 +0x194 fp=0xc000c5be90 sp=0xc000c5b950 pc=0x14ca5f4
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.9.1.1(0xc00005cb01)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:585 +0x765 fp=0xc000c5bf68 sp=0xc000c5be90 pc=0x14cc085
[2021-01-30T10:31:19.390Z] github.com/intel/pmem-csi/pkg/pmem-csi-operator/controller/deployment_test.TestDeploymentController.func1.9.1.3(0xc001542600)
[2021-01-30T10:31:19.390Z] 	/mnt/workspace/pmem-csi_PR-866/pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:595 +0x2a fp=0xc000c5bf80 sp=0xc000c5bf68 pc=0x14cc1aa
[2021-01-30T10:31:19.390Z] testing.tRunner(0xc001542600, 0xc000da6080)
[2021-01-30T10:31:19.390Z] 	/go/src/testing/testing.go:1127 +0xef fp=0xc000c5bfd0 sp=0xc000c5bf80 pc=0x521a6f
[2021-01-30T10:31:19.390Z] runtime.goexit()
[2021-01-30T10:31:19.390Z] 	/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000c5bfd8 sp=0xc000c5bfd0 pc=0x471081
[2021-01-30T10:31:19.390Z] created by testing.(*T).Run
[2021-01-30T10:31:19.390Z] 	/go/src/testing/testing.go:1178 +0x386
```

Also seen earlier, see commit 2bd9fd4911649be10b9989b53d87aeaf044c9b31 for an attempt at a workaround.

**Comment by pohly** [comment]
The `load.go:84` and the encoding of `NodeSelector` provides a good indication of what the map is which gets access concurrently: it must be the `NodeSelector` itself. It comes from `dep.Spec.NodeSelector`, which itself was generated by `dep := testcase.Deployment.DeepCopyObject().(*api.PmemCSIDeployment)`.

Or rather, should have been. A closer look at the generated `DeepCopyObject()` shows that it does *not* copy maps: https://github.com/intel/pmem-csi/blob/90dfa119a909640c06a7700dd3f973bef88ce38a/pkg/apis/pmemcsi/v1beta1/zz_generated.deepcopy.go#L77-L95

**Comment by pohly** [comment]
Duplicate of https://github.com/intel/pmem-csi/issues/852
