### ISSUE TITLE
test flake: unexpected restart of external-provisioner

### ISSUE THREAD

**Issue by pohly** [intel/pmem-csi#902]
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/devel/324/tests

```
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: F0211 04:46:07.939316       1 csi-provisioner.go:180] Error getting server version: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: goroutine 1 [running]:
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: k8s.io/klog/v2.stacks(0xc0000b0001, 0xc000110000, 0xa9, 0xce)
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: 	/workspace/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: k8s.io/klog/v2.(*loggingT).output(0x2604640, 0xc000000003, 0x0, 0x0, 0xc00042fc70, 0x2552643, 0x12, 0xb4, 0x0)
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: 	/workspace/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: k8s.io/klog/v2.(*loggingT).printf(0x2604640, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x199cc5f, 0x20, 0xc000048080, 0x1, ...)
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: 	/workspace/vendor/k8s.io/klog/v2/klog.go:750 +0x191
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: k8s.io/klog/v2.Fatalf(...)
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: 	/workspace/vendor/k8s.io/klog/v2/klog.go:1502
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: main.main()
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: 	/workspace/cmd/csi-provisioner/csi-provisioner.go:180 +0xa8e
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: 
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: goroutine 18 [chan receive]:
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: k8s.io/klog/v2.(*loggingT).flushDaemon(0x2604640)
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: 	/workspace/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: created by k8s.io/klog/v2.init.0
[2021-02-11T04:46:08.159Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: 	/workspace/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
[2021-02-11T04:46:09.496Z] pmem-csi-intel-com-node-p7xcz/external-provisioner@pmem..ker2: ==== end of pod log ===
```

**Comment by pohly** [comment]
From: https://github.com/kubernetes-csi/external-provisioner/blob/f937d0d4a1d88d866d95fad51148b686d9357cfc/cmd/csi-provisioner/csi-provisioner.go#L176-L181

Looks like an overloaded apiserver. Not sure whether we should relax our "no restart" check?

**Comment by pohly** [comment]
Not seen anymore.
